name: env

inputs:
  test_name:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: env
      shell: bash
      run: |
        echo "TARGET=${test_name}" >> "$GITHUB_ENV"
        echo "$TARGET"