name: github-actions
on: [push]

jobs:
  build:
   runs-on: ubuntu-latest
   container: #起動するコンテナイメージを指定
      image: node:16.14.0

   steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup-Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    # - name: Run
    #   run: docker run --rm -v "$(pwd)":/usr/src/app -w /usr/src/app node:latest sh -c "yarn global add typescript && yarn add lodash @types/lodash && tsc && node sample.js"
    - name: Install
      run: |
        yarn global add typescript
        yarn add lodash @types/lodash
        yarn install
    - name: Build and Run
      run: |
        yarn run tsc
        node sample.js
