name: test

on:
 workflow_dispatch:
  inputs:
    testes:
      type: string
      required: false
      description: aaa

jobs:
  test:
   runs-on: ubuntu-22.04
   steps:
     - name: check
       uses: actions/checkout@v4
     - name: test
       run: |
         echo ${{ github.event.inputs.testes }}
         echo  ${{ inputs.testes }}
  call:
    uses: ./.github/workflows/call.yml
    with:
      target: ${{ inputs.testes }} 
