# .github/workflows/tes.yml (修正済み)

name: test

on:
  workflow_dispatch:
    inputs:
      testes:
        type: string
        required: false
        description: aaa

jobs:
  # 1. 'test' ジョブの定義
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: check
        uses: actions/checkout@v4
      # 外部アクションの実行（"./env" はローカルアクションを想定）
      - name: env config
        uses: ./env
        with:
          test_name: ${{ github.event.inputs.testes }} # アクションの入力に値を渡す
      - name: test
        run: |
          # 実行ステップ内では、inputsコンテキストと github.event.inputs コンテキストのどちらも使えます。
          echo "inputs.testes: ${{ inputs.testes }}"
          echo "$TARGET"

  # 2. 'call' ジョブの定義 (再利用可能なワークフローを呼び出すジョブ)
  call_workflow: # ジョブには必ず名前をつけます
    uses: ./.github/workflows/call.yml
    # もし call.yml 側にパラメータを渡す場合は 'with:' を使います。
    with:
      target: ${{ inputs.testes }}
      testes: